---
- name: Run a webhook listener service
  hosts: all
  sources:
    - ansible.eda.webhook:
  rules:
    - name: Webhook event
      condition: "i" in event.payload.payload
      action:
        debug:
          msg: "Webhook triggered!"
